services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: saas-postgres
    environment:
      POSTGRES_DB: saas_platform
      POSTGRES_USER: saas_user
      POSTGRES_PASSWORD: saas_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/seed-data.sql:/docker-entrypoint-initdb.d/2-seed-data.sql

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: saas-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://postgres:5432/saas_platform
      - DATABASE_USERNAME=saas_user
      - DATABASE_PASSWORD=saas_password

  # Authentication Service
  auth-service:
    build: ./auth-service
    container_name: saas-auth-service
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://postgres:5432/saas_platform
      - DATABASE_USERNAME=saas_user
      - DATABASE_PASSWORD=saas_password
      - JWT_SECRET=mySuperSecretKeyWhichShouldBeOverridden

  # Tenant Service
  tenant-service:
    build: ./tenant-service
    container_name: saas-tenant-service
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://postgres:5432/saas_platform
      - DATABASE_USERNAME=saas_user
      - DATABASE_PASSWORD=saas_password

  # User Service
  user-service:
    build: ./user-service
    container_name: saas-user-service
    ports:
      - "8083:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://postgres:5432/saas_platform
      - DATABASE_USERNAME=saas_user
      - DATABASE_PASSWORD=saas_password

  # Module Service
  module-service:
    build: ./module-service
    container_name: saas-module-service
    ports:
      - "8084:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://postgres:5432/saas_platform
      - DATABASE_USERNAME=saas_user
      - DATABASE_PASSWORD=saas_password

  # Subscription Service
  subscription-service:
    build: ./subscription-service
    container_name: saas-subscription-service
    ports:
      - "8085:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://postgres:5432/saas_platform
      - DATABASE_USERNAME=saas_user
      - DATABASE_PASSWORD=saas_password

volumes:
  postgres_data:
