server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: lb://auth-service
          predicates: [ Path=/api/auth/** ]
        - id: tenant
          uri: lb://tenant-service
          predicates: [ Path=/api/tenants/** ]
        - id: user
          uri: lb://user-service
          predicates: [ Path=/api/users/** ]
        - id: module
          uri: lb://module-service
          predicates: [ Path=/api/modules/** ]
        - id: subscription
          uri: lb://subscription-service
          predicates: [ Path=/api/subscriptions/** ]

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
