server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://auth-service:8081
          predicates: [ Path=/api/auth/** ]
        - id: tenant
          uri: http://tenant-service:8082
          predicates: [ Path=/api/tenants/** ]
        - id: user
          uri: http://user-service:8083
          predicates: [ Path=/api/users/** ]
        - id: module
          uri: http://module-service:8084
          predicates: [ Path=/api/modules/** ]
        - id: subscription
          uri: http://subscription-service:8085
          predicates: [ Path=/api/subscriptions/** ]
